trigger:
- master

pool:
  vmImage: 'Ubuntu-20.04-latest'


variables:
  dockerId: yy520lwh                            # 阿里云 login username
  pwd: hao520..
  namespace: wenhaox                            # 阿里云 命名空间
  imageName: webnotebook                        # 阿里云 仓库名称
  registry: registry.cn-hangzhou.aliyuncs.com/wenhaox/webnotebook # 阿里云 公网地址
  dockerfilepath:  WebNotebook/Dockerfile       # Github Dockerfile相对路径


steps:
- script: |
    docker build -f $(dockerfilepath) -t $(imageName) .
    docker login -u $(dockerId) -p $(pwd) $(registry)
    docker tag $(imageName) $(registry)/$(namespace)/$(imageName)
    docker push $(registry)/$(namespace)/$(imageName)
  displayName: push to aliyun